config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurants#index'

  devise_for :users

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	belongs_to :user
	validates :name, length: {minimum: 3}, uniqueness: true
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


	def average_rating
		return 'N/A' if reviews.none?
		reviews.average(:rating)
		# reviews.inject(0) {|memo, review| memo + review.rating} / reviews.size
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
	has_many :endorsements
	validates :rating, inclusion: (1..5)
	validates_uniqueness_of :user_id, :scope => :restaurant_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :restaurants
  has_many :reviews

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    # user.name = auth.info.name   # assuming the user model has a name
    # user.image = auth.info.image # assuming the user model has an image
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

	def index
		@review = Review.find(params[:review_id])
	    @review.endorsements.create
	    respond_to do |format|
		    format.html {redirect_to restaurants_path}
		    format.json {render :json => {new_endorsement_count: @review.endorsements.count} }
  		end
	end
	# def create
	# 	@review = Review.find(params[:review_id])
	# 	@review.endorsements.create
	# 	render json: {new_endorsement_count: @review.endorsements.count}
	# end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :authenticate_user!, :except => [:index, :show]

	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = current_user.restaurants.new(params[:restaurant].permit(:name, :description, :image))
		if @restaurant.save
			redirect_to restaurants_path
		else
			render 'new'
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(params[:restaurant].permit(:name, :description, :image))
		redirect_to '/restaurants'
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = 'Restaurant deleted successfully'
		redirect_to '/restaurants'
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :authenticate_user!

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@hasReview = @restaurant.reviews.where(user_id: current_user.id)
		if @hasReview.count > 0
			flash[:alert] = 'You have already reviewed this restaurant'
			redirect_to restaurants_path
		end
		@review = Review.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@restaurant.reviews.create(review_params)
		redirect_to restaurants_path
	end

	def review_params
		params.require(:review).permit(:thoughts, :rating, :user_id)
	end

	def destroy
		# @restaurant = Restaurant.find(params[:restaurant_id])
		@review = Review.find(params[:review])
		@review.destroy
		redirect_to '/restaurants'
		flash[:notice] = 'Review deleted successfully'
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def star_rating(rating)
		return rating unless rating.respond_to?(:round)
		remainder = (5 - rating)
		"★" * rating.round + "☆" * remainder
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>
<% if user_signed_in? %>
	<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Sign in", new_user_session_path %>
	<%= link_to "Sign up", new_user_registration_path %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
	<%= f.file_field :image %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<h2><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %> </h2>
		<% if current_user == restaurant.user %>
			<%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>	
			<%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
		<% end %>
			<%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>

		<h3>Reviews for <%= restaurant.name %></h3> 
		<%= image_tag restaurant.image.url(:thumb) %>
		<h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>

		 <% if !restaurant.reviews.any? %>
		 	<p> No reviews</p>
		 <% else %>
			<ul>
				<% restaurant.reviews.each do |review| %>
					<li>
						<%= review.thoughts %>, <strong><%= review.rating %></strong>/5
						<%= link_to 'Endorse', review_endorsements_path(review), class: 'endorsements-link' %>
						<span class="endorsements_count"><%= review.endorsements.count %></span> endorsements
					</li>
					<% if current_user == review.user %>
						<%= link_to "Delete Review", review_path(restaurant, review: review), method: :delete %>	
					<% end %>	
				<% end %>
			</ul>
	<% end %>
	<% end %>
<% else %>
	<p> No restaurants yet</p>
<% end %>

<a href='/restaurants/new'>Add a restaurant</a>

app/views/restaurants/new.html.erb
<%= render "form" %>

<% if @restaurant.errors.any? %>
	<div id='errors'>
		<h2> <%= pluralize(@restaurant.errors.count, "error") %> Prohibited this restaurant from being saved: </h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>
<p><%= @restaurant.rating %></p>
<p><%= @restaurant.reviews.first %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>
	<%= f.label :rating %>
	<%= f.select :rating, (1..5) %>
	<%= f.submit 'Leave Review' %>
<% end %>